components_manager:
    static_config_validation:
        validate_all_components: false

    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        tracer:                              # Component that helps to trace execution times and requests in logs.
            service-name: vpn_manager         # "You know. You all know exactly who I am. Say my name. " (c)

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-v1-get-user-by-username:
            path: /v1/users/get-user-by-username
            method: POST
            task_processor: main-task-processor
        handler-v1-create-user:
            path: /v1/users/create-user
            method: POST
            task_processor: main-task-processor
        
        handler-v1-create-key:
            path: /v1/keys/create-key
            method: POST
            task_processor: main-task-processor
        handler-v1-get-key-by-id:
            path: /v1/keys/get-key-by-id
            method: POST
            task_processor: main-task-processor
        handler-v1-get-key-by-name:
            path: /v1/keys/get-key-by-name
            method: POST
            task_processor: main-task-processor

        postgres-db-1:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: false
            connlimit_mode: manual

        user-repository-component:
            task_processor: main-task-processor
        key-repository-component:
            task_processor: main-task-processor

        dns-client:
            fs-task-processor: fs-task-processor
